version: "3.7"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_database
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  node:
    container_name: node_docker
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - "db:database"
